# Generated by Django 4.2.8 on 2023-12-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.FloatField(max_length=100),
        ),
    ]
