# Generated by Django 4.2.8 on 2023-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_description_alter_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.FloatField(),
        ),
    ]
