# Generated by Django 4.2.8 on 2023-12-20 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название шоу')),
                ('description', models.TextField(blank=True, verbose_name='Дайте описание шоу')),
                ('image', models.ImageField(upload_to='shows/', verbose_name='добавте фото шоу')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(3000)], verbose_name='укажите цену')),
                ('genre', models.CharField(choices=[('Спортивная', 'Спортивная'), ('Комедиеное', 'Комедиеное'), ('Семейное', 'Семейное'), ('Детское', 'Детское')], max_length=100)),
                ('author', models.CharField(max_length=100, verbose_name='укажите автора')),
                ('trailer', models.URLField(blank=True, verbose_name='укажите ссылку на трейлер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
